<tr id="row_magepsycho_storepricing_import_setting">
    <td colspan="5">
        <div class="section-config">
            <div class="entry-edit-head admin__collapsible-block">
                <?= /* @noEscape */ __('To Import Prices (Regular, Special & Tier Price Importer) as per store view, please visit') ?>
                <a href="https://www.magepsycho.com/magento2-mass-regular-special-tier-group-price-importer.html?utm_source=extension-setting&utm_medium=banner&utm_campaign=m2-store-view-pricing" target="_blank" title="Magento 2 Regular, Special & Tier Price Importer">
                    <?= /* @noEscape */ __('Magento 2 Regular, Special & Tier Price Importer Extension') ?>
                </a>
            </div>
        </div>
    </td>
</tr>
